openapi: "3.0.0"
info:
  version: "1"
  title: ""
  description: ""
paths:
  /storyWithDetails:
    $ref: "./paths/storyWithDetails.yaml"
  /api:
    $ref: "./splitted/photon.yaml#/paths/~1api"
  /reverse:
    $ref: "./splitted/photon.yaml#/paths/~1reverse"
  /status:
    $ref: "./splitted/photon.yaml#/paths/~1status"
  /keywords:
    $ref: "./paths/keywords.yaml"
