openapi: "3.0.0"
info:
  version: "1"
  title: ""
  description: ""
paths:
  /storyWithDetails:
    get:
      operationId: getStoryWithDetails
      description: ""
      tags:
        - stories
      parameters:
        - in: query
          name: keyword
          schema:
            type: string
        - in: query
          name: lat
          schema:
            type: number
            format: double
        - in: query
          name: lon
          schema:
            type: number
            format: double
        - in: query
          name: radiusInMeters
          schema:
            type: number
            format: double
        - in: query
          name: startDate
          schema:
            type: string
        - in: query
          name: endDate
          schema:
            type: string
        - in: query
          name: pageNumber
          schema:
            type: integer
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: sortBy
          schema:
            type: string
        - in: query
          name: ascending
          schema:
            type: boolean
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StoryWithDetailsPaged"
  /api:
    $ref: "./splitted/photon.yaml#/paths/~1api"
  /reverse:
    $ref: "./splitted/photon.yaml#/paths/~1reverse"
  /status:
    $ref: "./splitted/photon.yaml#/paths/~1status"

components:
  securitySchemes: {}
  schemas:
    StoryWithDetails:
      required:
        - storyUrl
        - storyDateTime
        - storyTitle
        - locationLabel
        - locationBoundingbox
        - locationBoundingboxArea
        - locationPoint
        - keywords
      properties:
        storyUrl:
          nullable: false
          type: string
        storyDateTime:
          nullable: false
          type: string
          format: date-time
        storyTitle:
          nullable: false
          type: string
        locationLabel:
          nullable: false
          type: string
        locationBoundingbox:
          nullable: false
          type: array
          items:
            type: number
        locationBoundingboxArea:
          nullable: false
          type: number
        locationPoint:
          nullable: false
          $ref: "#/components/schemas/GeomPoint"
        keywords:
          nullable: false
          type: array
          items:
            type: string
    StoryWithDetailsPaged:
      required:
        - content
        - page
      properties:
        content:
          nullable: false
          type: array
          items:
            $ref: "#/components/schemas/StoryWithDetails"
        page:
          nullable: false
          $ref: "#/components/schemas/PageInfo"
    PageInfo:
      required:
        - size
        - number
        - totalElements
        - totalPages
      properties:
        size:
          nullable: false
          type: integer
        number:
          nullable: false
          type: integer
        totalElements:
          nullable: false
          type: integer
        totalPages:
          nullable: false
          type: integer
    GeomPoint:
      required:
        - type
        - coordinates
      properties:
        type:
          nullable: false
          type: string
        coordinates:
          nullable: false
          type: array
          items:
            type: number
    Location:
      properties:
        geometry:
          nullable: false
          $ref: "#/components/schemas/GeomPoint"
